#version 450

#ifndef ASSIGN_COMP_
#define ASSIGN_COMP_

#include <mylib/mylib.glsl>


layout (
    local_size_x_id = 1, local_size_x = 1,
    local_size_y_id = 2, local_size_y = 1,
    local_size_z_id = 3, local_size_z = 1
) in;

layout(binding = 0) buffer out0 {
    float out_buffer[];
};

void main() {

    const uint index = gl_GlobalInvocationID.x;

    // A_VERY_IMPORTANT_CONSTANT is defined in mylib/mylib.glsl
    out_buffer[index] = A_VERY_IMPORTANT_CONSTANT;
}

#endif // ASSIGN_COMP_
